#!/bin/bash

pmonitor_file=/tmp/.pmonitor.me
if [ ! -f $pmonitor_file ];then
    touch $pmonitor_file
fi
if [ $# -lt 1 ];then
    echo "Usage:"
    echo "      nohup_run.sh < program start commend >"
fi

run_commend="nohup"
for param in $*
do 
    run_commend="$run_commend $param"
done
run_commend="$run_commend &"

cat $pmonitor_file | grep "${run_commend}"
exist=$?
if [ $exist -eq 0 ];then
    line=`cat $pmonitor_file | grep "${run_commend}"`
    for token in $line
    do
        pid=token
        break
    done
    echo $pid

    ps -ax | awk '{ print $1  }' | grep -e "^${pid}$"
    $c_pid=$?
    if [ $c_pid -eq 0 ];then
        echo "error:this program exist!!!"
        echo "      only one process allow per program"
        exit
    fi
    sed -i "/{$pid}/d" $pmonitor_file
fi

eval $run_commend
pid=$!
echo "$pid $run_commend" >> $pmonitor_file


